=== lucide-icons/lucide/icon.schema.json
{
  "$id": "https://lucide.dev/icons.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$vocabulary": {
    "https://json-schema.org/draft/2020-12/vocab/core": true,
    "https://json-schema.org/draft/2020-12/vocab/applicator": true,
    "https://json-schema.org/draft/2020-12/vocab/unevaluated": true,
    "https://json-schema.org/draft/2020-12/vocab/validation": true,
    "https://json-schema.org/draft/2020-12/vocab/meta-data": true,
    "https://json-schema.org/draft/2020-12/vocab/format-annotation": true,
    "https://json-schema.org/draft/2020-12/vocab/content": true
  },
  "title": "Lucide Icons icon schema",
  "type": "object",
  "additionalProperties": false,
  "required": ["$schema", "contributors", "categories", "tags", "use-cases"],
  "properties": {
    "$schema": {
      "type": "string"
    },
    "aliases": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": ["name"],
        "properties": {
          "name": {
            "type": "string"
          },
          "deprecated": {
            "const": true
          },
          "deprecationReason": {
            "$ref": "#/$defs/aliasDeprecationReasons"
          },
          "toBeRemovedInVersion": {
            "$ref": "#/$defs/versionNumber",
            "description": "The version this icon will be removed in."
          }
        },
        "dependentRequired": {
          "deprecated": ["deprecationReason"],
          "deprecationReason": ["deprecated"],
          "toBeRemovedInVersion": ["deprecated"]
        }
      },
      "uniqueItems": true
    },
    "categories": {
      "type": "array",
      "items": {
        "anyOf": [
          {
            "type": "string",
            "enum": [
              "accessibility",
              "account",
              "animals",
              "arrows",
              "buildings",
              "charts",
              "communication",
              "connectivity",
              "cursors",
              "design",
              "development",
              "devices",
              "emoji",
              "files",
              "finance",
              "food-beverage",
              "gaming",
              "home",
              "layout",
              "letters-digits",
              "mail",
              "math",
              "medical",
              "multimedia",
              "nature",
              "navigation",
              "notifications",
              "people",
              "photography",
              "science",
              "seasons",
              "security",
              "shapes",
              "shopping",
              "social",
              "sports",
              "sustainability",
              "text",
              "time",
              "tools",
              "transportation",
              "travel",
              "weather"
            ]
          },
          {
            "type": "string",
            "pattern": "^\\$extends:[a-z0-9]+(-[a-z0-9]+)*$"
          }
        ]
      },
      "uniqueItems": true
    },
    "contributors": {
      "type": "array",
      "items": {
        "type": "string",
        "if": {
          "pattern": "^\\$[a-zA-Z]"
        },
        "then": {
          "pattern": "^\\$extends:[a-z0-9]+(-[a-z0-9]+)*$"
        }
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string",
        "if": {
          "pattern": "^\\$[a-zA-Z]"
        },
        "then": {
          "pattern": "^\\$extends:[a-z0-9]+(-[a-z0-9]+)*$"
        }
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "use-cases": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 0,
      "uniqueItems": true
    },
    "deprecated": {
      "const": true
    },
    "deprecationReason": {
      "$ref": "#/$defs/iconDeprecationReasons"
    },
    "toBeRemovedInVersion": {
      "$ref": "#/$defs/versionNumber",
      "description": "The version this icon will be removed in."
    }
  },
  "dependentRequired": {
    "deprecated": ["deprecationReason"],
    "deprecationReason": ["deprecated"],
    "toBeRemovedInVersion": ["deprecated"]
  },
  "$defs": {
    "iconDeprecationReasons": {
      "type": "string",
      "enum": ["icon.design", "icon.use-case"]
    },
    "aliasDeprecationReasons": {
      "type": "string",
      "enum": ["alias.typo", "alias.name", "alias.duplicate"]
    },
    "versionNumber": {
      "type": "string",
      "pattern": "v[0-9]+(\\.[0-9]+)+"
    }
  },
  "description": "A JSON Schema for icons defined by Lucide Icons."
}

=== lucide-icons/lucide/icons/message-square-more.json
{
  "$schema": "../icon.schema.json",
  "contributors": [
    "danielbayley",
    "karsa-mistmere"
  ],
  "use-cases": [],
  "tags": [
    "$extends:message-square",
    "typing",
    "writing",
    "responding",
    "ellipsis",
    "etc",
    "et cetera",
    "...",
    "…"
  ],
  "categories": [
    "$extends:message-square"
  ]
}

=== lucide-icons/lucide/icons/mail-clock.json
{
  "$schema": "../icon.schema.json",
  "contributors": [
    "colebemis",
    "karsa-mistmere",
    "ericfennis"
  ],
  "use-cases": [
    "Represents scheduled communication",
    "Represents send later icons",
    "Indication scheduled mail",
    "Indication delayed delivery features in messaging, email, and productivity tools"
  ],
  "tags": [
    "$extends:mail",
    "scheduled",
    "delayed",
    "send later",
    "delivery",
    "reminder",
    "pending",
    "outgoing",
    "timer"
  ],
  "categories": [
    "$extends:mail",
    "time",
    "notifications",
    "communication"
  ]
}

=== lucide-icons/lucide/icons/list-chevrons-down-up.json
{
  "$schema": "../icon.schema.json",
  "contributors": [
    "colebemis",
    "ericfennis",
    "ocavue",
    "jguddas",
    "PeterlitsZo",
    "mittalyashu",
    "juliankellydesign",
    "karsa-mistmere"
  ],
  "use-cases": [],
  "tags": [
    "$extends:list",
    "$group:direction-down",
    "$group:direction-up",
    "items",
    "collapse",
    "expand",
    "details",
    "disclosure",
    "show",
    "hide",
    "toggle",
    "accordion",
    "more",
    "less",
    "fold",
    "unfold"
  ],
  "categories": [
    "$extends:list",
    "arrows"
  ]
}

=== lucide-icons/lucide/icons/pen-off.json
{
  "$schema": "../icon.schema.json",
  "contributors": [
    "colebemis",
    "csandman",
    "mittalyashu",
    "ericfennis",
    "karsa-mistmere"
  ],
  "use-cases": [],
  "tags": [
    "$extends:pen",
    "$group:off",
    "non-editable",
    "locked",
    "read-only",
    "unmodifiable",
    "frozen",
    "restricted"
  ],
  "categories": [
    "$extends:pen"
  ]
}

=== lucide-icons/lucide/icons/circle-star.json
{
  "$schema": "../taxonomy/schemas/icon.schema.json",
  "contributors": [
    "karsa-mistmere"
  ],
  "use-cases": [],
  "tags": [
    "badge",
    "medal",
    "honour",
    "decoration",
    "order",
    "pin",
    "laurel",
    "trophy",
    "medallion",
    "insignia",
    "bronze",
    "silver",
    "gold"
  ],
  "categories": [
    "sports",
    "gaming"
  ]
}

=== lucide-icons/lucide/icons/film.json
{
  "$schema": "../taxonomy/schemas/icon.schema.json",
  "contributors": [
    "colebemis",
    "ericfennis",
    "danielbayley"
  ],
  "use-cases": [],
  "tags": [
    "movie",
    "video",
    "reel",
    "camera",
    "cinema",
    "entertainment"
  ],
  "categories": [
    "photography",
    "multimedia"
  ]
}

=== lucide-icons/lucide/icons/banknote-arrow-up.json
{
  "$schema": "../icon.schema.json",
  "contributors": [
    "AnnaSasDev",
    "joffx",
    "ericfennis",
    "mittalyashu"
  ],
  "use-cases": [],
  "tags": [
    "$extends:banknote",
    "bill",
    "funds",
    "transaction",
    "cash",
    "finance",
    "deposit",
    "earnings",
    "income",
    "in",
    "credit",
    "prepaid",
    "growth",
    "increase"
  ],
  "categories": [
    "$extends:banknote"
  ]
}

=== lucide-icons/lucide/icons/panel-top-dashed.json
{
  "$schema": "../icon.schema.json",
  "contributors": [
    "danielbayley",
    "ericfennis",
    "irvineacosta"
  ],
  "use-cases": [],
  "tags": [
    "$extends:panel-top",
    "menu bar",
    "show",
    "reveal",
    "padding",
    "margin",
    "guide",
    "layout",
    "bleed"
  ],
  "categories": [
    "layout"
  ],
  "aliases": [
    {
      "name": "panel-top-inactive",
      "deprecationReason": "alias.name",
      "deprecated": true
    }
  ]
}
