=== lucide-icons/lucide/icon.schema.json
{
  "$id": "https://lucide.dev/icons.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$vocabulary": {
    "https://json-schema.org/draft/2020-12/vocab/core": true,
    "https://json-schema.org/draft/2020-12/vocab/applicator": true,
    "https://json-schema.org/draft/2020-12/vocab/unevaluated": true,
    "https://json-schema.org/draft/2020-12/vocab/validation": true,
    "https://json-schema.org/draft/2020-12/vocab/meta-data": true,
    "https://json-schema.org/draft/2020-12/vocab/format-annotation": true,
    "https://json-schema.org/draft/2020-12/vocab/content": true
  },
  "title": "Lucide Icons icon schema",
  "type": "object",
  "additionalProperties": false,
  "required": ["$schema", "contributors", "categories", "tags", "use-cases"],
  "properties": {
    "$schema": {
      "type": "string"
    },
    "aliases": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": ["name"],
        "properties": {
          "name": {
            "type": "string"
          },
          "deprecated": {
            "const": true
          },
          "deprecationReason": {
            "$ref": "#/$defs/aliasDeprecationReasons"
          },
          "toBeRemovedInVersion": {
            "$ref": "#/$defs/versionNumber",
            "description": "The version this icon will be removed in."
          }
        },
        "dependentRequired": {
          "deprecated": ["deprecationReason"],
          "deprecationReason": ["deprecated"],
          "toBeRemovedInVersion": ["deprecated"]
        }
      },
      "uniqueItems": true
    },
    "categories": {
      "type": "array",
      "items": {
        "anyOf": [
          {
            "type": "string",
            "enum": [
              "accessibility",
              "account",
              "animals",
              "arrows",
              "buildings",
              "charts",
              "communication",
              "connectivity",
              "cursors",
              "design",
              "development",
              "devices",
              "emoji",
              "files",
              "finance",
              "food-beverage",
              "gaming",
              "home",
              "layout",
              "letters-digits",
              "mail",
              "math",
              "medical",
              "multimedia",
              "nature",
              "navigation",
              "notifications",
              "people",
              "photography",
              "science",
              "seasons",
              "security",
              "shapes",
              "shopping",
              "social",
              "sports",
              "sustainability",
              "text",
              "time",
              "tools",
              "transportation",
              "travel",
              "weather"
            ]
          },
          {
            "type": "string",
            "pattern": "^\\$extends:[a-z0-9]+(-[a-z0-9]+)*$"
          }
        ]
      },
      "uniqueItems": true
    },
    "contributors": {
      "type": "array",
      "items": {
        "type": "string",
        "if": {
          "pattern": "^\\$[a-zA-Z]"
        },
        "then": {
          "pattern": "^\\$extends:[a-z0-9]+(-[a-z0-9]+)*$"
        }
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string",
        "if": {
          "pattern": "^\\$[a-zA-Z]"
        },
        "then": {
          "pattern": "^\\$extends:[a-z0-9]+(-[a-z0-9]+)*$"
        }
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "use-cases": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 0,
      "uniqueItems": true
    },
    "deprecated": {
      "const": true
    },
    "deprecationReason": {
      "$ref": "#/$defs/iconDeprecationReasons"
    },
    "toBeRemovedInVersion": {
      "$ref": "#/$defs/versionNumber",
      "description": "The version this icon will be removed in."
    }
  },
  "dependentRequired": {
    "deprecated": ["deprecationReason"],
    "deprecationReason": ["deprecated"],
    "toBeRemovedInVersion": ["deprecated"]
  },
  "$defs": {
    "iconDeprecationReasons": {
      "type": "string",
      "enum": ["icon.design", "icon.use-case"]
    },
    "aliasDeprecationReasons": {
      "type": "string",
      "enum": ["alias.typo", "alias.name", "alias.duplicate"]
    },
    "versionNumber": {
      "type": "string",
      "pattern": "v[0-9]+(\\.[0-9]+)+"
    }
  },
  "description": "A JSON Schema for icons defined by Lucide Icons."
}

=== lucide-icons/lucide/icons/bubbles.json
{
  "$schema": "../icon.schema.json",
  "contributors": [
    "vqh2602",
    "jguddas",
    "karsa-mistmere"
  ],
  "use-cases": [],
  "tags": [
    "water",
    "cleaning",
    "soap",
    "bath",
    "hygiene",
    "freshness",
    "wash",
    "foam",
    "cleanliness",
    "shampoo",
    "purity",
    "splash",
    "lightness",
    "airy",
    "relaxation",
    "spa",
    "bubbly",
    "fluid",
    "floating",
    "drop"
  ],
  "categories": [
    "home"
  ]
}

=== lucide-icons/lucide/icons/kanban.json
{
  "$schema": "../icon.schema.json",
  "contributors": [
    "danielbayley",
    "karsa-mistmere"
  ],
  "use-cases": [],
  "tags": [
    "projects",
    "manage",
    "overview",
    "board",
    "tickets",
    "issues",
    "roadmap",
    "plan",
    "intentions",
    "productivity",
    "work",
    "agile",
    "code",
    "coding"
  ],
  "categories": [
    "charts",
    "development"
  ]
}

=== lucide-icons/lucide/icons/brain-circuit.json
{
  "$schema": "../icon.schema.json",
  "contributors": [
    "karsa-mistmere",
    "jguddas",
    "it-is-not",
    "ericfennis"
  ],
  "use-cases": [],
  "tags": [
    "$extends:brain",
    "deep learning",
    "machine learning",
    "computing"
  ],
  "categories": [
    "science",
    "development"
  ]
}

=== lucide-icons/lucide/icons/letter-b.json
{
  "$schema": "../icon.schema.json",
  "contributors": [
    "colebemis",
    "csandman",
    "ericfennis",
    "jguddas",
    "karsa-mistmere"
  ],
  "use-cases": [
    "indicating bold text formatting",
    "labeling blood type B",
    "representing bytes in computing contexts",
    "indicating a B-side track or recording",
    "marking a bus or transit line"
  ],
  "tags": [
    "strong",
    "emphasis",
    "format",
    "alphabet",
    "character",
    "uppercase",
    "bold",
    "blood type",
    "byte",
    "computing",
    "b-side",
    "bus",
    "transit",
    "text",
    "font",
    "typography"
  ],
  "categories": [
    "letters-digits",
    "text"
  ],
  "aliases": [
    {
      "name": "bold"
    }
  ]
}

=== lucide-icons/lucide/icons/daffodil.json
{
  "$schema": "../icon.schema.json",
  "contributors": [
    "ryck"
  ],
  "use-cases": [
    "Cancer awareness campaigns, fundraising and Daffodil Day donation pages",
    "Welsh content and St David's Day events, as the national flower of Wales",
    "Seasonal spring and Easter content in calendars, shops and newsletters",
    "Gardening, bulb planting and plant identification apps",
    "March birth flower in gift, jewelry and greeting card apps"
  ],
  "tags": [
    "flower",
    "narcissus",
    "jonquil",
    "spring",
    "nature",
    "plant",
    "bloom",
    "wales",
    "easter",
    "trumpet",
    "corona",
    "bulb",
    "charity",
    "fundraising",
    "cancer",
    "awareness",
    "st david's day",
    "national flower",
    "birth flower",
    "march"
  ],
  "categories": [
    "nature",
    "sustainability"
  ]
}

=== lucide-icons/lucide/icons/square-sigma.json
{
  "$schema": "../icon.schema.json",
  "contributors": [
    "danielbayley"
  ],
  "use-cases": [],
  "tags": [
    "$group:letter",
    "sum",
    "calculate",
    "formula",
    "math",
    "enumeration",
    "enumerate"
  ],
  "categories": [
    "letters-digits",
    "text",
    "math"
  ],
  "aliases": [
    {
      "name": "sigma-square",
      "deprecationReason": "alias.name",
      "deprecated": true
    }
  ]
}

=== lucide-icons/lucide/icons/circle-dot.json
{
  "$schema": "../icon.schema.json",
  "contributors": [
    "karsa-mistmere"
  ],
  "use-cases": [],
  "tags": [
    "pending",
    "dot",
    "progress",
    "issue",
    "code",
    "coding",
    "version control",
    "choices",
    "multiple choice",
    "choose",
    "album",
    "music",
    "songs",
    "format",
    "cd",
    "dvd",
    "vinyl",
    "sleeve",
    "cover",
    "platinum",
    "compilation",
    "ep",
    "recording",
    "playback",
    "spin",
    "rotate",
    "rpm",
    "dj"
  ],
  "categories": [
    "$extends:circle",
    "development"
  ]
}

=== lucide-icons/lucide/icons/circle-letter-q.json
{
  "$schema": "../icon.schema.json",
  "contributors": [
    "karsa-mistmere"
  ],
  "use-cases": [
    "Indicating questions or help prompts",
    "Representing queues or waiting lines",
    "Representing electric charge in scientific contexts",
    "Indicating quality labels or ratings"
  ],
  "tags": [
    "$group:letter",
    "uppercase",
    "question",
    "help",
    "queue",
    "charge",
    "electricity",
    "quality",
    "rating"
  ],
  "categories": [
    "letters-digits"
  ]
}
